### ISSUE TITLE
Over One

### ISSUE THREAD

**Issue by mdoallo** [utn-ba-rf-lab/gr-eas#5]
Si la señal que ingresa pasa el valor uno debe quedarse en uno.
No tengo claro que el problema sea del bloque o del HDL.
Agregué un ejemplo (examples/over-one.grc).
No recuerdo como snifear el puerto ttyUSB1 para ver de qué lado está el error.
Si envío la secuencia (0,0.2, 0.4, 0.6,0.8,1,**1.2**,0,0.2, 0.4, 0.6,0.8,1,**1.2**)
A la salida sale esto:
![TEK0000](https://github.com/utn-ba-rf-lab/gr-serializer/assets/62174402/0b8f1824-f8ba-4e84-ae9b-cb728e1a6e77)

**Comment by leandrobottinelli** [comment]
Deje actualizado en la rama **sat_overflow** el codigo con la saturacion de la salida para valores absolutos mayores a 1 en la entrada. No lo pude probar con mercurial porque parece no estar conectada, asi que lo probe numericamente.

Con los comandos que copio debajo se puede redireccionar un puerto a otro. En el ejemplo, se redirecciona _ttyS20_ a _ttyS21_, y se pone una terminal como sniffer de ttyS21. Del otro lado lado hay que configurar al flowgraph para que escriba en _ttyS20_


```
socat -u -u pty,raw,echo=0,link=/dev/ttyS20 pty,raw,echo=0,link=/dev/ttyS21&
sudo screen /dev/ttyS21
```

Igualmente en este caso los valores de entradas no van a ser caracteres ascii legibles.

**Comment by mdoallo** [comment]
Con el código de esta rama satura bien, no se pasa del valor máximo de DAC . Pero esta rama tiene un problema con el flujo de las muestras que no tiene el bloque está en la rama main.
Armé un video con el mismo código de GNU Radio para comparar, los primeros diez segundos con rama satura y los diez siguientes con rama main.
[https://photos.app.goo.gl/MLgko6ASCCmzJn8fA](https://photos.app.goo.gl/MLgko6ASCCmzJn8fA)
El código es 1tone.grc que está en examples de la rama main.

**Comment by mdoallo** [comment]
Probé la rama "sat_overflow" funciona bien y no toma la CPU.
![GNU_Radio_Running](https://github.com/user-attachments/assets/f58571c6-52e4-45f1-9107-6a11ca7dc876)

Aquí se observa que superé el valor uno. Así sale en el osciloscopio:
![DS0003](https://github.com/user-attachments/assets/f23072eb-ba81-40ce-981b-b544e4b756eb)

¡Buen trabajo!, se puede funcionar la rama.
